-- Postgres extensions required by tests.
CREATE EXTENSION IF NOT EXISTS citext;
CREATE EXTENSION IF NOT EXISTS ltree;
CREATE EXTENSION IF NOT EXISTS cube;
CREATE EXTENSION IF NOT EXISTS btree_gist;

-- Composite / enum types referenced from describe tests.
DROP TYPE IF EXISTS status;
CREATE TYPE status AS ENUM ('new', 'open', 'closed');

DROP TYPE IF EXISTS inventory_item CASCADE;
CREATE TYPE inventory_item AS (
    name         text,
    supplier_id  int4,
    price        int8
);

-- `tweet` — used by describe/error/postgres tests.
DROP TABLE IF EXISTS tweet_reply;
DROP TABLE IF EXISTS tweet;
CREATE TABLE tweet (
    id         int8 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamptz NOT NULL DEFAULT now(),
    text       text        NOT NULL,
    owner_id   int8
);

CREATE TABLE tweet_reply (
    id         int8 PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    tweet_id   int8 NOT NULL REFERENCES tweet(id),
    text       text NOT NULL
);

-- `products` — check-constraint failure test.
DROP TABLE IF EXISTS products;
CREATE TABLE products (
    id    int4 PRIMARY KEY,
    name  text NOT NULL,
    price int4 NOT NULL CONSTRAINT products_price_check CHECK (price > 0)
);

-- `circles` — exclusion-constraint failure test.
DROP TABLE IF EXISTS circles;
CREATE TABLE circles (
    c circle,
    EXCLUDE USING gist (c WITH &&)
);
